/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.company.hotelreservation.gui;

import az.company.hotelreservation.model.Customer;
import az.company.hotelreservation.service.abstracts.AddressService;
import az.company.hotelreservation.service.abstracts.CustomerService;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asim Babayev
 */
public class MainFrame extends javax.swing.JFrame {
    private CustomerService customerService;
    private AddressService addressService;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public MainFrame(CustomerService customerService,AddressService addressService){
        this();
        this.customerService = customerService;
        this.addressService = addressService;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJp = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        sidebarJp = new javax.swing.JPanel();
        customerBtn = new javax.swing.JButton();
        bookingBtn = new javax.swing.JButton();
        hotelBtn = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        contentJp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerJp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        editBtn.setText("Edit");

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");

        javax.swing.GroupLayout headerJpLayout = new javax.swing.GroupLayout(headerJp);
        headerJp.setLayout(headerJpLayout);
        headerJpLayout.setHorizontalGroup(
            headerJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerJpLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerJpLayout.setVerticalGroup(
            headerJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerJpLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(headerJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        sidebarJp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        customerBtn.setText("Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        bookingBtn.setText("Booking");

        hotelBtn.setText("Hotel");

        paymentBtn.setText("Payment");

        javax.swing.GroupLayout sidebarJpLayout = new javax.swing.GroupLayout(sidebarJp);
        sidebarJp.setLayout(sidebarJpLayout);
        sidebarJpLayout.setHorizontalGroup(
            sidebarJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarJpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(customerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(paymentBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarJpLayout.setVerticalGroup(
            sidebarJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarJpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentJp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout contentJpLayout = new javax.swing.GroupLayout(contentJp);
        contentJp.setLayout(contentJpLayout);
        contentJpLayout.setHorizontalGroup(
            contentJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentJpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                .addContainerGap())
        );
        contentJpLayout.setVerticalGroup(
            contentJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentJpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarJp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerJp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidebarJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        showCustomerData();
        
    }//GEN-LAST:event_customerBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        NewCustomerFrame customerFrame = new NewCustomerFrame(customerService,addressService);
        customerFrame.setVisible(true);
    }//GEN-LAST:event_newBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingBtn;
    private javax.swing.JPanel contentJp;
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel headerJp;
    private javax.swing.JButton hotelBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newBtn;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JPanel sidebarJp;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    private void showCustomerData() {
        try {
            DefaultTableModel customerTable = new DefaultTableModel();
            tbl.setModel(customerTable);
            customerTable.addColumn("Id");
            customerTable.addColumn("Name");
            customerTable.addColumn("Surname");
            customerTable.addColumn("Password");
            customerTable.addColumn("Date Of Birth");
            customerTable.addColumn("Gender");
            customerTable.addColumn("Image");
            customerTable.addColumn("Account Status");
            customerTable.addColumn("AddressId");
            customerTable.addColumn("Country");
            customerTable.addColumn("City");
            customerTable.addColumn("Region");
            customerTable.addColumn("Address Line");
            customerTable.addColumn("ContactId");
            customerTable.addColumn("Phone");
            customerTable.addColumn("Email");
            customerTable.addColumn("PersonId");
            customerTable.addColumn("Customer Type");
            List<Customer> customers = (List<Customer>) customerService.getAll();
            for(Customer customer : customers){
                Object[] object = new Object[]{
                    customer.getId(),
                    customer.getName(),
                    customer.getSurname(),
                    customer.getPassword(),
                    customer.getDateOfBirth(),
                    customer.getGender(),
                    customer.getImage(),
                    customer.getAccountStatus(),
                    customer.getAddressId(),
                    customer.getAddress().getParent().getParent().getParent().getName(),
                    customer.getAddress().getParent().getParent().getName(),
                    customer.getAddress().getParent().getName(),
                    customer.getAddress().getName(),
                    customer.getContactId(),
                    customer.getContact().getPhone(),
                    customer.getContact().getEmail(),
                    customer.getPersonId(),
                    customer.getCustomerType()
                };
                customerTable.addRow(object);
            }
            customerTable.fireTableDataChanged();
        } catch (Exception e) {
        }
    }
}
